# Generated by Django 3.2.15 on 2022-09-28 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openformsclient", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuration",
            options={"verbose_name": "Open Forms client configuration"},
        ),
    ]
