# Generated by Django 4.1.1 on 2022-09-24 06:39

from django.db import migrations, models

import openformsclient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("form", openformsclient.models.OpenFormsField(blank=True)),
            ],
        ),
    ]
