# Generated by Django 3.2.15 on 2022-09-30 12:11

from django.db import migrations, models

import openformsclient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "form_slug",
                    openformsclient.models.OpenFormsSlugField(
                        blank=True, db_index=False, max_length=100
                    ),
                ),
                (
                    "form_uuid",
                    openformsclient.models.OpenFormsUUIDField(blank=True, null=True),
                ),
            ],
        ),
    ]
